/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksRefreshBalneazioneRouteImport } from './routes/api/public/hooks/refresh-balneazione'
import { Route as ApiPublicHooksRefreshAvvisiRouteImport } from './routes/api/public/hooks/refresh-avvisi'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshBalneazioneRoute =
  ApiPublicHooksRefreshBalneazioneRouteImport.update({
    id: '/api/public/hooks/refresh-balneazione',
    path: '/api/public/hooks/refresh-balneazione',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshAvvisiRoute =
  ApiPublicHooksRefreshAvvisiRouteImport.update({
    id: '/api/public/hooks/refresh-avvisi',
    path: '/api/public/hooks/refresh-avvisi',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/hooks/refresh-avvisi': typeof ApiPublicHooksRefreshAvvisiRoute
  '/api/public/hooks/refresh-balneazione': typeof ApiPublicHooksRefreshBalneazioneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/hooks/refresh-avvisi': typeof ApiPublicHooksRefreshAvvisiRoute
  '/api/public/hooks/refresh-balneazione': typeof ApiPublicHooksRefreshBalneazioneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/hooks/refresh-avvisi': typeof ApiPublicHooksRefreshAvvisiRoute
  '/api/public/hooks/refresh-balneazione': typeof ApiPublicHooksRefreshBalneazioneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/api/public/hooks/refresh-avvisi'
    | '/api/public/hooks/refresh-balneazione'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/api/public/hooks/refresh-avvisi'
    | '/api/public/hooks/refresh-balneazione'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/api/public/hooks/refresh-avvisi'
    | '/api/public/hooks/refresh-balneazione'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksRefreshAvvisiRoute: typeof ApiPublicHooksRefreshAvvisiRoute
  ApiPublicHooksRefreshBalneazioneRoute: typeof ApiPublicHooksRefreshBalneazioneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-balneazione': {
      id: '/api/public/hooks/refresh-balneazione'
      path: '/api/public/hooks/refresh-balneazione'
      fullPath: '/api/public/hooks/refresh-balneazione'
      preLoaderRoute: typeof ApiPublicHooksRefreshBalneazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-avvisi': {
      id: '/api/public/hooks/refresh-avvisi'
      path: '/api/public/hooks/refresh-avvisi'
      fullPath: '/api/public/hooks/refresh-avvisi'
      preLoaderRoute: typeof ApiPublicHooksRefreshAvvisiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksRefreshAvvisiRoute: ApiPublicHooksRefreshAvvisiRoute,
  ApiPublicHooksRefreshBalneazioneRoute: ApiPublicHooksRefreshBalneazioneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
